### ISSUE TITLE
PG::ConnectionBad Is the server running locally

### ISSUE THREAD

**Issue by agustindesolminihac** [IIC2143/Syllabus#34]
Hola, en el último paso, al correr rails s, e intentar conectarme me dice esto
![Captura de pantalla (39)](https://user-images.githubusercontent.com/49526698/186931163-6b25f3e7-8dca-4585-a12d-c2a7881e7cd1.png)

**Comment by meretamal** [comment]
Hola, eso es porque no está corriendo tu servicio de postgres en el puerto 5432 (que es el puerto que usa por default).

Asegúrate primero de que esté corriendo (con el comando que sale en la guía de setup de tu sistema operativo).

**Comment by ValeeRamirez** [comment]
Hola, a mi me pasa lo mismo pero si tengo corriendo el servicio (con el comando rails s)

**Comment by BenediktKd** [comment]
Me sigue saliendo el mismo error, aunque esté corriendo postgres.

**Comment by meretamal** [comment]
Si abres una consola de psql y corres `\conninfo` que output te sale?

**Comment by BenediktKd** [comment]
![Captura de pantalla 2022-09-07 165538](https://user-images.githubusercontent.com/80901100/188965419-e159b716-b801-425f-96dd-e18795e9e9bc.png)

Tiene por default 5433, estoy tratando de cambiarlo, pero no encuentro la manera.

**Comment by meretamal** [comment]
Hola, es probable que tengas otro servicio ocupando el puerto 5432. Lo que podrías hacer es cambiar tu archivo **database.yml** por lo siguiente:
```yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  port: : <%= ENV["DB_PORT"] %>

development:
  <<: *default
  database: <nombre proyecto>_development

test:
  <<: *default
  database: <nombre proyecto>_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
```

y agregar la variable `DB_PORT=5433` a tu archivo **.env**.
