### ISSUE TITLE
[Setup Windows] Solución a error "rails db:create could not connect to server"

### ISSUE THREAD

**Issue by ElTioAndresCabezas** [IIC2143/Syllabus#49]
Saludos
Escribo para todas las personas que probablemente esten teniendo problemas en el paso 10 del Setup para Ubuntu / Windows, en donde al correr `rails db:create` da error diciendo que no se logró conectar a la base de datos de PostgreSQL.
Es muy probable que esto se deba a un error en los ports de PostgreSQL. La solución la encontre en este <a href="https://dewetblomerus.com/2016/05/10/postgres-could-not-connect-to-server.html">sitio web</a>. Estos son los pasos para resolver el problema
1. Identificar el puerto de PostgreSQL
`sudo -u postgres psql -c "SHOW port;"`
2. Insertar el puerto en el archivo `database.yml`. El original se verá asi
```yaml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <nombre proyecto>_development
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>

test:
  <<: *default
  database: <nombre proyecto>_test

production:
  <<: *default
  #url: /var/run/postgresql/.s.PGSQL.5433
  url: <%= ENV["DATABASE_URL"] %>
```
Si su puerto fuera el 5433, por ejemplo, deben cambiar el default: &default así
```yaml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5433
```
Con esto, el problema debería quedar resuelto.
Lo escribo por aqui debido a que ni yo ni los ayudantes logramos identificar que era lo que estaba pasando, y es probable que a alguna otra persona le esté ocurriendo lo mismo.
Muchas gracias por leer!
Andrés Cabezas
